version: '3.5'
services:
  amsterdam:
    build:
      dockerfile: Dockerfile
      context: ./domains/amsterdam/
      args:
        - BUILD_ENV=acc
        - DOCKER_REGISTRY=docker-registry.data.amsterdam.nl:5000
        - DOCKER_REGISTRY_PATH=/ois/
        - DOCKER_IMAGE=signalsfrontend
        - DOCKER_IMAGE_TAG=latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 3001:80
  amsterdamsebos:
    build:
      dockerfile: Dockerfile
      context: ./domains/amsterdamsebos/
      args:
        - BUILD_ENV=acc
        - DOCKER_REGISTRY=docker-registry.data.amsterdam.nl:5000
        - DOCKER_REGISTRY_PATH=/ois/
        - DOCKER_IMAGE=signalsfrontend
        - DOCKER_IMAGE_TAG=latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 3001:80
  weesp:
    build:
      dockerfile: Dockerfile
      context: ./domains/weesp/
      args:
        - BUILD_ENV=acc
        - DOCKER_REGISTRY=docker-registry.data.amsterdam.nl:5000
        - DOCKER_REGISTRY_PATH=/ois/
        - DOCKER_IMAGE=signalsfrontend
        - DOCKER_IMAGE_TAG=latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 3001:80
